### ISSUE TITLE
Training errors

### ISSUE THREAD

**Issue by Ha0Tang** [xh-liu/CC-FPSE#6]
----------------- End -------------------
train.py --name coco_cc_fpse --mpdist --netG condconv --dist_url tcp://:8000 --num_servers 1 --netD fpse --lambda_feat 20 --dataset_mode coco --dataroot datasets/coco_stuff --batchSize 1 --niter 100 --niter_decay 100 --use_vae
Use GPU: 5 for training
Use GPU: 3 for training
Use GPU: 6 for training
Use GPU: 7 for training
Use GPU: 2 for training
Traceback (most recent call last):
  File "train.py", line 97, in <module>
    main()
  File "train.py", line 29, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, idx_server, opt))
  File "/home/htang/anaconda3/envs/python3pytorch11/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/htang/anaconda3/envs/python3pytorch11/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 5 terminated with the following error:
Traceback (most recent call last):
  File "/home/htang/anaconda3/envs/python3pytorch11/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/htang/projects/CC-FPSE/train.py", line 37, in main_worker
    dist.init_process_group(backend='nccl', init_method=opt.dist_url, world_size=world_size, rank=rank)
  File "/home/htang/anaconda3/envs/python3pytorch11/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 400, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/htang/anaconda3/envs/python3pytorch11/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 95, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. torch.distributed.TCPStore(arg0: str, arg1: int, arg2: int, arg3: bool)

Invoked with: None, 8000, 8, False

**Comment by Rubiel1** [comment]
I have the same error, did you solve it @Ha0Tang ?

**Comment by Ha0Tang** [comment]
Not yet @Rubiel1

**Comment by Rubiel1** [comment]
I suspect this has to do with the pytorch.distributed library, but I have never used it so I asked on the pytorch forum: https://discuss.pytorch.org/t/adapt-code-with-pytorch-distributed-to-only-one-gpu/73520

**Comment by Rubiel1** [comment]
As the link said, change the following line on the train.py file:
`torch.distributed.init_process_group(backend='nccl', init_method=opt.dist_url, world_size=1, rank=0)`
 also, the value opt.dist_url needs to be changed to something like ""tcp://localhost:23456""

Make sure you put  one gpu per node @Ha0Tang

**Comment by Ha0Tang** [comment]
did you solve it @Rubiel1 ?

**Comment by qqlu** [comment]
You could replace "--dist_url tcp://$ip:8000" with "--dist_url tcp://127.0.0.1:8000" in train.sh.

**Comment by Ha0Tang** [comment]
train.py --name cc_fpse_city --mpdist --netG condconv --dist_url tcp://127.0.0.1:8000 --num_servers 1 --netD fpse --lambda_feat 20 --dataset_mode cityscapes --dataroot ./datasets/Cityscapes --batchSize 16 --niter 100 --niter_decay 100
Use GPU: 0 for training
Use GPU: 4 for training
Use GPU: 2 for training
Use GPU: 5 for training
Use GPU: 7 for training
Use GPU: 3 for training
Use GPU: 6 for training
Use GPU: 1 for training
Traceback (most recent call last):
  File "train.py", line 97, in <module>
    main()
  File "train.py", line 29, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, idx_server, opt))
  File "/data/anaconda3/envs/pytorch_v1.0/lib/python3.5/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/data/anaconda3/envs/pytorch_v1.0/lib/python3.5/site-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/data/anaconda3/envs/pytorch_v1.0/lib/python3.5/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/CC-FPSE/train.py", line 37, in main_worker
    dist.init_process_group(backend='nccl', init_method=opt.dist_url, world_size=world_size, rank=0)
  File "/data/anaconda3/envs/pytorch_v1.0/lib/python3.5/site-packages/torch/distributed/distributed_c10d.py", line 406, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/data/anaconda3/envs/pytorch_v1.0/lib/python3.5/site-packages/torch/distributed/rendezvous.py", line 95, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon)
RuntimeError: Address already in use

**Comment by Ha0Tang** [comment]
@qqlu Do you know how to train on 8 GPUs?

**Comment by Rubiel1** [comment]
I never tried with more than one gpu as I was just exploring techniques.

**Comment by Ha0Tang** [comment]
Solved.

**Comment by Rubiel1** [comment]
What was the problem? How did you solve it?

**Comment by fatemeh-slh** [comment]
@Ha0Tang Can you share how did you solve it? I still get this error:
`RuntimeError: Address already in use`

**Comment by Ha0Tang** [comment]
Changing 8000 to another one such as 8001 will solve the error `RuntimeError: Address already in use`.

**Comment by fatemeh-slh** [comment]
@Ha0Tang Thanks for your quick reply! The address issue is sloved now, however, the code almost does nothing when reaches to 
`dist.init_process_group(backend='nccl', init_method=opt.dist_url, world_size=1, rank=1)`

After about a minute or two, it gets a timeout error:

```Use GPU: 0 for training
before dist init
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/hdd/sadegh/Pix2Pix/CC-FPSE/train.py", line 38, in main_worker
    dist.init_process_group(backend='nccl', init_method=opt.dist_url, world_size=1, rank=1)
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 397, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 120, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon)
RuntimeError: connect() timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fatemeh/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/fatemeh/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
KeyboardInterrupt
Traceback (most recent call last):
  File "train.py", line 100, in <module>
    main()
  File "train.py", line 29, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, idx_server, opt))
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/hdd/sadegh/Pix2Pix/CC-FPSE/train.py", line 38, in main_worker
    dist.init_process_group(backend='nccl', init_method=opt.dist_url, world_size=1, rank=1)
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 397, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 120, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon)
RuntimeError: connect() timed out.
```

Do you have any idea what might cause this issue?

**Comment by Ha0Tang** [comment]
How many GPUs are you using?

**Comment by fatemeh-slh** [comment]
one GPU, here is the command I use:

`python train.py --name ds_fpse --mpdist --netG condconv --netD fpse --lambda_feat 20 --dataset_mode cartoon --dataroot datasets/ds --batchSize 64 --niter 100 --niter_decay 100 --use_vae --dist_url tcp://localhost:8000 --no_instance --ngpus_per_node 1`

**Comment by Ha0Tang** [comment]
Changing `dist.init_process_group(backend='nccl', init_method=opt.dist_url, world_size=1, rank=1)` to the original one, and everything should be fine.

**Comment by fatemeh-slh** [comment]
Great! Thanks that solved the issue. Now, it raises another error:

```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/hdd/sadegh/Pix2Pix/CC-FPSE/train.py", line 66, in main_worker
    trainer.run_generator_one_step(data_i)
  File "/hdd/sadegh/Pix2Pix/CC-FPSE/trainers/pix2pix_trainer.py", line 25, in run_generator_one_step
    g_losses, generated = self.pix2pix_model(data, mode='generator')
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/hdd/sadegh/Pix2Pix/CC-FPSE/models/pix2pix_model.py", line 39, in forward
    input_semantics, real_image)
  File "/hdd/sadegh/Pix2Pix/CC-FPSE/models/pix2pix_model.py", line 129, in compute_generator_loss
    input_semantics, real_image, compute_kld_loss=self.opt.use_vae)
  File "/hdd/sadegh/Pix2Pix/CC-FPSE/models/pix2pix_model.py", line 175, in generate_fake
    z, mu, logvar = self.encode_z(real_image)
  File "/hdd/sadegh/Pix2Pix/CC-FPSE/models/pix2pix_model.py", line 167, in encode_z
    mu, logvar = self.netE(real_image)
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/hdd/sadegh/Pix2Pix/CC-FPSE/models/networks/encoder.py", line 38, in forward
    x = self.layer1(x)
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 524, in __call__
    result = hook(self, input)
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/nn/utils/spectral_norm.py", line 99, in __call__
    setattr(module, self.name, self.compute_weight(module, do_power_iteration=module.training))
  File "/home/fatemeh/anaconda3/lib/python3.7/site-packages/torch/nn/utils/spectral_norm.py", line 78, in compute_weight
    v = normalize(torch.mv(weight_mat.t(), u), dim=0, eps=self.eps, out=v)
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
```

**Comment by fatemeh-slh** [comment]
I guess I can fix the issue, but, if I couldn't, I will let you know here...

**Comment by Ha0Tang** [comment]
Can you try the Cityscapes dataset first and see if it works?
